ALTER TABLE agent_runs
  DROP CONSTRAINT IF EXISTS agent_runs_status_check;

ALTER TABLE agent_runs
  ADD CONSTRAINT agent_runs_status_check CHECK (status IN (
    'INIT','PRECHECK','HOTSPOT_DISCOVERY','SLICE_SELECT',
    'RETRIEVE_EVIDENCE','BUILD_PROMPT','GENERATE_PATCH','VALIDATE_PATCH',
    'APPLY_PATCH','RUN_BUILD','RUN_TEST','RUN_LINT','DIAGNOSE',
    'SCORE_PROGRESS','ROLLBACK','SUCCESS','STOP_NO_PROGRESS',
    'STOP_MAX_ITERS','STOP_HARD_ERROR',
    'RETRIEVE','GENERATE','APPLY','EXECUTE','STOP','FAILED'
  ));
